# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 084c397ada2916b69fcd561577c4715b4c9b4b57a08507d13ab590f0a348fed3f951bc3e8c013a35fd7c5198a13db243b0c46348f533c1f26ea4b5a564c18496

test:
  secret_key_base: d91752f5ee0dee3658267875931d8cade26c020f6fcfbae1b4c17c2cff4e13e42d71801d6fd2a984be3ef1a2c9f31fcb35ad67f6a14e6b5e8849454e37c9885b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
